version: 2

jobs:
  build:
    docker:
      - image: docker:stable
        environment:
          DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - checkout
      - run: apk add make curl
      - setup_remote_docker:
          version: 18.09.3
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run: docker version
      - run: make prepare-old
      - run: make build-push