name: build

on: [push]

jobs:
  build:
    name: build images and push
    runs-on: ubuntu-latest

    steps:

      - name: install qemu
        run: docker run --rm --privileged hypriot/qemu-register

      - name: checkout
        uses: actions/checkout@v1

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: install buildx and app
        run: make prepare
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

      - name: build and push
        run: make build-push
        env:
          CI_NAME: github
